### PR TITLE
Massive update on twod materials generation and analysis tools, band structure calculations, calibrate workflow tools, chem_sub

### PR DESCRIPTION
**Pull request by joshgabriel**

### CODE REVIEW

**Comment by matk86** [comment]
Thanks, can you fix the failing tests?

**Comment by joshgabriel** [comment]
Yes will do. I am looking at the logs.

**Comment by joshgabriel** [comment]
@ashtonmv From the logs, the failing tests are in nosetests twod_materials most likely because of the unique API key matching for travis to my fork, can you take a look at this please?

**Comment by matk86** [comment]
testfiles, such as AECAR*, DOSCAR, XDATCAR etc ,  are those really needed? Unnecessary repo bloat should be avoided at all cost(github doesnt provide unlimited storage)

**Comment by matk86** [comment]
to fix the tests: for testing purposes its better to load the structure(and other data) from files instead of fetching it from MP via the apikey...

**Comment by joshgabriel** [comment]
I agree it makes sense to load structures instead of querying through the API key.

**Comment by joshgabriel** [comment]
Thanks @ashtonmv. I resolved the travis.yml file conflict and waiting on the travis checks to complete.

**Pull request merged**
