### PR TITLE
Utils fixme

### PR DESCRIPTION
**Pull request by joshgabriel**
Make job submission script more user configurable according to their batch system instead of hostname

### CODE REVIEW

**Comment by joshgabriel** [comment]
I do not understand what codecov/patch report is, does anyone understand, @matk86 @ashtonmv @SeveMonahan ?

**Comment by ashtonmv** [comment]
It's measuring how much of *the code you're adding* is getting hit during testing, which only 36% is. It looks like someone has specified that the patch you're adding must have a coverage equal to or greater than the current coverage for the entire code base (55%), which is reasonable but may not be strictly necessary when we're making small changes. I think it's a good rule of thumb though.

**Comment by matk86** [comment]
i didnt setup the codecov integration

**Comment by joshgabriel** [comment]
ok, I just pushed a commit including some unit tests for get_run_cmmnd. perhaps can be used as a test case if it improves the coverage report. Thanks for finishing the merge anyways, will look for more ways to improve the coverage score (any thoughts if 55% is a good score?) with unit tests of more functions.

**Pull request merged**
