### PR TITLE
Latest twod_materials integration

### PR DESCRIPTION
**Pull request by ashtonmv**
This has all the latest twod_materials modules and passes all tests. mpinterfaces.rest is also included as a module.

### CODE REVIEW

**Comment by matk86** [comment]
what happened?

**Comment by ashtonmv** [comment]
I meant to create a pull request to Josh’s forked version of MPInterfaces but didn’t select the right base fork. My bad.

Michael

On Mar 1, 2017, 10:46 AM -0500, Kiran Mathew <notifications@github.com>, wrote:

what happened?

**Comment by matk86** [comment]
@ashtonmv @joshgabriel you guys can take over this repo...happy to hand it over :+1: 
reopening the PR..

**Comment by joshgabriel** [comment]
@matk86 Thanks Kiran. We will also be happy to make a version 2.0 release when we have more of the updates with complete test integration on the other branches in dev on my fork. I am closing this request for now and will open a request from my fork's master branch. I will be happy to have permission (perhaps you need to grant me) to approve the final pull request.

Also please add Joshua Paul and Seve as members of the henniggroup organization. Thanks for adding Michael! 

Cheers,
Josh

**Comment by matk86** [comment]
ok. what are their usernames?

**Comment by joshgabriel** [comment]
SeveMonahan and JTPaul 

Thanks!

**Comment by joshgabriel** [comment]
And I also see the email on my access rights. Thank you!

**Comment by matk86** [comment]
added them both, both you and michael are admins now...

**Pull request closed without merging**
